// Mocks generated by Mockito 5.4.4 from annotations
// in for_u_partners/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;
import 'dart:ui' as _i21;

import 'package:cloud_firestore/cloud_firestore.dart' as _i33;
import 'package:dio/dio.dart' as _i3;
import 'package:flutter/material.dart' as _i19;
import 'package:for_u_partners/app/models/course_model.dart' as _i5;
import 'package:for_u_partners/app/models/login_model.dart' as _i24;
import 'package:for_u_partners/app/models/pressing_depot_models/depot_detail_model.dart'
    as _i11;
import 'package:for_u_partners/app/models/pressing_depot_models/depot_model.dart'
    as _i30;
import 'package:for_u_partners/app/models/pressing_depot_models/planned_depot_model.dart'
    as _i12;
import 'package:for_u_partners/app/models/pressing_model.dart' as _i28;
import 'package:for_u_partners/app/models/pressing_ramassage_models/ramassage_detail_model.dart'
    as _i9;
import 'package:for_u_partners/app/models/pressing_ramassage_models/ramassage_model.dart'
    as _i29;
import 'package:for_u_partners/app/models/pressing_ramassage_models/ramassage_statut_model.dart'
    as _i10;
import 'package:for_u_partners/app/models/ramasseur_models/facture_ramassage_model.dart'
    as _i16;
import 'package:for_u_partners/app/models/ramasseur_models/ramasseur_demand_detail.dart'
    as _i15;
import 'package:for_u_partners/app/models/ramasseur_models/ramasseur_demand_model.dart'
    as _i14;
import 'package:for_u_partners/app/models/register_model.dart' as _i25;
import 'package:for_u_partners/app/models/wallet_model.dart' as _i13;
import 'package:for_u_partners/models/daily_stats_model.dart' as _i6;
import 'package:for_u_partners/models/global_stats_model.dart' as _i7;
import 'package:for_u_partners/models/user_model.dart' as _i8;
import 'package:for_u_partners/services/auth_service.dart' as _i23;
import 'package:for_u_partners/services/chat_service.dart' as _i32;
import 'package:for_u_partners/services/driver_service.dart' as _i26;
import 'package:for_u_partners/services/pickers_service.dart' as _i34;
import 'package:for_u_partners/services/pressing_service.dart' as _i27;
import 'package:for_u_partners/services/sharedpreferences_service.dart' as _i4;
import 'package:for_u_partners/services/wallet_service.dart' as _i31;
import 'package:for_u_partners/ui/views/delivery/courses_delivery/courses_delivery_viewmodel.dart'
    as _i22;
import 'package:http_parser/http_parser.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:stacked_services/stacked_services.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMediaType_0 extends _i1.SmartFake implements _i2.MediaType {
  _FakeMediaType_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFormData_1 extends _i1.SmartFake implements _i3.FormData {
  _FakeFormData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedpreferencesService_2 extends _i1.SmartFake
    implements _i4.SharedpreferencesService {
  _FakeSharedpreferencesService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFactureCourse_3 extends _i1.SmartFake implements _i5.FactureCourse {
  _FakeFactureCourse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourseDetail_4 extends _i1.SmartFake implements _i5.CourseDetail {
  _FakeCourseDetail_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDailyStats_5 extends _i1.SmartFake implements _i6.DailyStats {
  _FakeDailyStats_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalStats_6 extends _i1.SmartFake implements _i7.GlobalStats {
  _FakeGlobalStats_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_7 extends _i1.SmartFake implements _i8.UserModel {
  _FakeUserModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRamassageDetail_8 extends _i1.SmartFake
    implements _i9.RamassageDetail {
  _FakeRamassageDetail_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRamassageStatutModel_9 extends _i1.SmartFake
    implements _i10.RamassageStatutModel {
  _FakeRamassageStatutModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRdv_10 extends _i1.SmartFake implements _i11.Rdv {
  _FakeRdv_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlannedDepotModel_11 extends _i1.SmartFake
    implements _i12.PlannedDepotModel {
  _FakePlannedDepotModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletModel_12 extends _i1.SmartFake implements _i13.WalletModel {
  _FakeWalletModel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRamasseurDemand_13 extends _i1.SmartFake
    implements _i14.RamasseurDemand {
  _FakeRamasseurDemand_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRamasseurDemandDetail_14 extends _i1.SmartFake
    implements _i15.RamasseurDemandDetail {
  _FakeRamasseurDemandDetail_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFactureRamassageModel_15 extends _i1.SmartFake
    implements _i16.FactureRamassageModel {
  _FakeFactureRamassageModel_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i17.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i19.GlobalKey<_i19.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i19.GlobalKey<_i19.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i17.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<T?>? navigateWithTransition<T>(
    _i19.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i19.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i17.Transition? transitionClass,
    _i17.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? replaceWithTransition<T>(
    _i19.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i19.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i17.Transition? transitionClass,
    _i17.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i19.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i19.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? navigateToView<T>(
    _i19.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i19.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i17.Transition? transition,
    _i17.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i19.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? clearStackAndShowView<T>(
    _i19.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? clearTillFirstAndShowView<T>(
    _i19.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);

  @override
  _i20.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i19.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i20.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i17.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i17.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<_i17.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i20.Future<_i17.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i20.Future<_i17.SheetResponse<dynamic>?>.value(),
      ) as _i20.Future<_i17.SheetResponse<dynamic>?>);

  @override
  _i20.Future<_i17.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i21.Color? barrierColor = const _i21.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i20.Future<_i17.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i20.Future<_i17.SheetResponse<T>?>.value(),
      ) as _i20.Future<_i17.SheetResponse<T>?>);

  @override
  void completeSheet(_i17.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i17.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i17.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i19.Widget Function(
      _i19.BuildContext,
      _i17.DialogRequest<dynamic>,
      dynamic Function(_i17.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<_i17.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i21.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i21.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i19.RouteSettings? routeSettings,
    _i19.GlobalKey<_i19.NavigatorState>? navigatorKey,
    _i17.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i20.Future<_i17.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i20.Future<_i17.DialogResponse<dynamic>?>.value(),
      ) as _i20.Future<_i17.DialogResponse<dynamic>?>);

  @override
  _i20.Future<_i17.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i21.Color? barrierColor = const _i21.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    _i19.RouteSettings? routeSettings,
    _i19.GlobalKey<_i19.NavigatorState>? navigatorKey,
    _i19.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i20.Future<_i17.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i20.Future<_i17.DialogResponse<T>?>.value(),
      ) as _i20.Future<_i17.DialogResponse<T>?>);

  @override
  _i20.Future<_i17.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i21.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i21.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i19.RouteSettings? routeSettings,
    _i17.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i20.Future<_i17.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i20.Future<_i17.DialogResponse<dynamic>?>.value(),
      ) as _i20.Future<_i17.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i17.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SharedpreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedpreferencesService extends _i1.Mock
    implements _i4.SharedpreferencesService {
  @override
  _i20.Future<void> saveToken(dynamic token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> saveUserType(dynamic type) => (super.noSuchMethod(
        Invocation.method(
          #saveUserType,
          [type],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getUserType() => (super.noSuchMethod(
        Invocation.method(
          #getUserType,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> removeUserType() => (super.noSuchMethod(
        Invocation.method(
          #removeUserType,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setOnlineStatus(bool? isOnline) => (super.noSuchMethod(
        Invocation.method(
          #setOnlineStatus,
          [isOnline],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<bool?> getOnlineStatus() => (super.noSuchMethod(
        Invocation.method(
          #getOnlineStatus,
          [],
        ),
        returnValue: _i20.Future<bool?>.value(),
        returnValueForMissingStub: _i20.Future<bool?>.value(),
      ) as _i20.Future<bool?>);

  @override
  _i20.Future<void> setBottomSheetType(_i22.RamassageBottomSheetType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBottomSheetType,
          [type],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<_i22.RamassageBottomSheetType?> getBottomSheetType() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBottomSheetType,
          [],
        ),
        returnValue: _i20.Future<_i22.RamassageBottomSheetType?>.value(),
        returnValueForMissingStub:
            _i20.Future<_i22.RamassageBottomSheetType?>.value(),
      ) as _i20.Future<_i22.RamassageBottomSheetType?>);

  @override
  _i20.Future<void> setAcceptedDemandeId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setAcceptedDemandeId,
          [id],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getAcceptedDemandeId() => (super.noSuchMethod(
        Invocation.method(
          #getAcceptedDemandeId,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> clearBottomSheetState() => (super.noSuchMethod(
        Invocation.method(
          #clearBottomSheetState,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> saveUserId(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [id],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> removeUserId() => (super.noSuchMethod(
        Invocation.method(
          #removeUserId,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> saveUserTypeId(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #saveUserTypeId,
          [id],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getUserTypeId() => (super.noSuchMethod(
        Invocation.method(
          #getUserTypeId,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> removeUserTypeId() => (super.noSuchMethod(
        Invocation.method(
          #removeUserTypeId,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> saveUserName(dynamic name) => (super.noSuchMethod(
        Invocation.method(
          #saveUserName,
          [name],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getUserName() => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> removeUserName() => (super.noSuchMethod(
        Invocation.method(
          #removeUserName,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> saveProfilStatuts(dynamic statuts) => (super.noSuchMethod(
        Invocation.method(
          #saveProfilStatuts,
          [statuts],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<String?> getProfilStatuts() => (super.noSuchMethod(
        Invocation.method(
          #getProfilStatuts,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> removeProfilStatuts() => (super.noSuchMethod(
        Invocation.method(
          #removeProfilStatuts,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i23.AuthService {
  @override
  _i20.Future<void> login(
    _i24.LoginModel? loginModel,
    _i19.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            loginModel,
            context,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<Map<String, String>> getAuthenticatedHeaders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthenticatedHeaders,
          [],
        ),
        returnValue: _i20.Future<Map<String, String>>.value(<String, String>{}),
        returnValueForMissingStub:
            _i20.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i20.Future<Map<String, String>>);

  @override
  _i20.Future<bool> checkPhoneNumberExists(String? phoneNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPhoneNumberExists,
          [phoneNumber],
        ),
        returnValue: _i20.Future<bool>.value(false),
        returnValueForMissingStub: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  _i2.MediaType getMediaTypeFromFileName(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaTypeFromFileName,
          [filePath],
        ),
        returnValue: _FakeMediaType_0(
          this,
          Invocation.method(
            #getMediaTypeFromFileName,
            [filePath],
          ),
        ),
        returnValueForMissingStub: _FakeMediaType_0(
          this,
          Invocation.method(
            #getMediaTypeFromFileName,
            [filePath],
          ),
        ),
      ) as _i2.MediaType);

  @override
  _i20.Future<_i3.FormData> registrationModelToFormData(
          _i25.RegistrationModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #registrationModelToFormData,
          [model],
        ),
        returnValue: _i20.Future<_i3.FormData>.value(_FakeFormData_1(
          this,
          Invocation.method(
            #registrationModelToFormData,
            [model],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i3.FormData>.value(_FakeFormData_1(
          this,
          Invocation.method(
            #registrationModelToFormData,
            [model],
          ),
        )),
      ) as _i20.Future<_i3.FormData>);

  @override
  _i20.Future<void> register(
    _i25.RegistrationModel? registrationModel,
    _i19.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            registrationModel,
            context,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [DriverService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverService extends _i1.Mock implements _i26.DriverService {
  @override
  _i4.SharedpreferencesService get sharedPreferencesService =>
      (super.noSuchMethod(
        Invocation.getter(#sharedPreferencesService),
        returnValue: _FakeSharedpreferencesService_2(
          this,
          Invocation.getter(#sharedPreferencesService),
        ),
        returnValueForMissingStub: _FakeSharedpreferencesService_2(
          this,
          Invocation.getter(#sharedPreferencesService),
        ),
      ) as _i4.SharedpreferencesService);

  @override
  _i20.Future<void> goOnline() => (super.noSuchMethod(
        Invocation.method(
          #goOnline,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> goOffline() => (super.noSuchMethod(
        Invocation.method(
          #goOffline,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<List<_i26.DriverLocation>> getOnlineDrivers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnlineDrivers,
          [],
        ),
        returnValue: _i20.Future<List<_i26.DriverLocation>>.value(
            <_i26.DriverLocation>[]),
        returnValueForMissingStub: _i20.Future<List<_i26.DriverLocation>>.value(
            <_i26.DriverLocation>[]),
      ) as _i20.Future<List<_i26.DriverLocation>>);

  @override
  _i20.Future<void> acceptCourse(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #acceptCourse,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> rejectCourse(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #rejectCourse,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> confirmArrival(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #confirmArrival,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> startCourse(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #startCourse,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> startPause(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #startPause,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> stopPause(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #stopPause,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> completeCourse(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #completeCourse,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<Map<String, dynamic>> getRideDetails(int? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRideDetails,
          [courseId],
        ),
        returnValue:
            _i20.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i20.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<_i5.FactureCourse> fetchFactureCourse(int? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFactureCourse,
          [courseId],
        ),
        returnValue: _i20.Future<_i5.FactureCourse>.value(_FakeFactureCourse_3(
          this,
          Invocation.method(
            #fetchFactureCourse,
            [courseId],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i5.FactureCourse>.value(_FakeFactureCourse_3(
          this,
          Invocation.method(
            #fetchFactureCourse,
            [courseId],
          ),
        )),
      ) as _i20.Future<_i5.FactureCourse>);

  @override
  _i20.Future<List<_i5.CoursePendingModel>> fetchCoursesPending() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCoursesPending,
          [],
        ),
        returnValue: _i20.Future<List<_i5.CoursePendingModel>>.value(
            <_i5.CoursePendingModel>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i5.CoursePendingModel>>.value(
                <_i5.CoursePendingModel>[]),
      ) as _i20.Future<List<_i5.CoursePendingModel>>);

  @override
  _i20.Future<List<_i5.CourseAssignedItem>> fetchCourses() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCourses,
          [],
        ),
        returnValue: _i20.Future<List<_i5.CourseAssignedItem>>.value(
            <_i5.CourseAssignedItem>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i5.CourseAssignedItem>>.value(
                <_i5.CourseAssignedItem>[]),
      ) as _i20.Future<List<_i5.CourseAssignedItem>>);

  @override
  _i20.Future<_i5.CourseDetail> fetchCourseDetail(int? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCourseDetail,
          [courseId],
        ),
        returnValue: _i20.Future<_i5.CourseDetail>.value(_FakeCourseDetail_4(
          this,
          Invocation.method(
            #fetchCourseDetail,
            [courseId],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i5.CourseDetail>.value(_FakeCourseDetail_4(
          this,
          Invocation.method(
            #fetchCourseDetail,
            [courseId],
          ),
        )),
      ) as _i20.Future<_i5.CourseDetail>);

  @override
  _i20.Future<double> fetchWalletSold() => (super.noSuchMethod(
        Invocation.method(
          #fetchWalletSold,
          [],
        ),
        returnValue: _i20.Future<double>.value(0.0),
        returnValueForMissingStub: _i20.Future<double>.value(0.0),
      ) as _i20.Future<double>);

  @override
  _i20.Future<_i6.DailyStats> fetchDailyStats() => (super.noSuchMethod(
        Invocation.method(
          #fetchDailyStats,
          [],
        ),
        returnValue: _i20.Future<_i6.DailyStats>.value(_FakeDailyStats_5(
          this,
          Invocation.method(
            #fetchDailyStats,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i6.DailyStats>.value(_FakeDailyStats_5(
          this,
          Invocation.method(
            #fetchDailyStats,
            [],
          ),
        )),
      ) as _i20.Future<_i6.DailyStats>);

  @override
  _i20.Future<_i7.GlobalStats> fetchGlobalStats() => (super.noSuchMethod(
        Invocation.method(
          #fetchGlobalStats,
          [],
        ),
        returnValue: _i20.Future<_i7.GlobalStats>.value(_FakeGlobalStats_6(
          this,
          Invocation.method(
            #fetchGlobalStats,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i7.GlobalStats>.value(_FakeGlobalStats_6(
          this,
          Invocation.method(
            #fetchGlobalStats,
            [],
          ),
        )),
      ) as _i20.Future<_i7.GlobalStats>);

  @override
  _i20.Future<_i8.UserModel> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i20.Future<_i8.UserModel>.value(_FakeUserModel_7(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i8.UserModel>.value(_FakeUserModel_7(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i20.Future<_i8.UserModel>);

  @override
  _i20.Future<_i8.UserModel> updateUserProfile({
    required String? nom,
    required String? prenom,
    required String? email,
    required String? telephone,
    String? adresse,
    String? dateNaissance,
    String? genre,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #nom: nom,
            #prenom: prenom,
            #email: email,
            #telephone: telephone,
            #adresse: adresse,
            #dateNaissance: dateNaissance,
            #genre: genre,
          },
        ),
        returnValue: _i20.Future<_i8.UserModel>.value(_FakeUserModel_7(
          this,
          Invocation.method(
            #updateUserProfile,
            [],
            {
              #nom: nom,
              #prenom: prenom,
              #email: email,
              #telephone: telephone,
              #adresse: adresse,
              #dateNaissance: dateNaissance,
              #genre: genre,
            },
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i8.UserModel>.value(_FakeUserModel_7(
          this,
          Invocation.method(
            #updateUserProfile,
            [],
            {
              #nom: nom,
              #prenom: prenom,
              #email: email,
              #telephone: telephone,
              #adresse: adresse,
              #dateNaissance: dateNaissance,
              #genre: genre,
            },
          ),
        )),
      ) as _i20.Future<_i8.UserModel>);

  @override
  _i20.Future<List<Map<String, dynamic>>> getCoursesList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursesList,
          [],
        ),
        returnValue: _i20.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i20.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i20.Future<List<Map<String, dynamic>>>);

  @override
  _i20.Future<Map<String, dynamic>> getCourseDetails(int? courseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseDetails,
          [courseId],
        ),
        returnValue:
            _i20.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i20.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<void> notifyClient(int? courseId) => (super.noSuchMethod(
        Invocation.method(
          #notifyClient,
          [courseId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> updateWallet(
    int? amount,
    _i19.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWallet,
          [
            amount,
            context,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> postdriverheartbeat(
    double? lat,
    double? long,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postdriverheartbeat,
          [
            lat,
            long,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [PressingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPressingService extends _i1.Mock implements _i27.PressingService {
  @override
  _i20.Future<_i28.PressingResponse?> getPressingInfo() => (super.noSuchMethod(
        Invocation.method(
          #getPressingInfo,
          [],
        ),
        returnValue: _i20.Future<_i28.PressingResponse?>.value(),
        returnValueForMissingStub: _i20.Future<_i28.PressingResponse?>.value(),
      ) as _i20.Future<_i28.PressingResponse?>);

  @override
  _i20.Future<List<_i29.Ramassage>> getRamassagesList() => (super.noSuchMethod(
        Invocation.method(
          #getRamassagesList,
          [],
        ),
        returnValue:
            _i20.Future<List<_i29.Ramassage>>.value(<_i29.Ramassage>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i29.Ramassage>>.value(<_i29.Ramassage>[]),
      ) as _i20.Future<List<_i29.Ramassage>>);

  @override
  _i20.Future<_i9.RamassageDetail> getRamassageDetailComplet(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRamassageDetailComplet,
          [id],
        ),
        returnValue:
            _i20.Future<_i9.RamassageDetail>.value(_FakeRamassageDetail_8(
          this,
          Invocation.method(
            #getRamassageDetailComplet,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i9.RamassageDetail>.value(_FakeRamassageDetail_8(
          this,
          Invocation.method(
            #getRamassageDetailComplet,
            [id],
          ),
        )),
      ) as _i20.Future<_i9.RamassageDetail>);

  @override
  _i20.Future<_i10.RamassageStatutModel> updateRamassageStatut(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRamassageStatut,
          [id],
        ),
        returnValue: _i20.Future<_i10.RamassageStatutModel>.value(
            _FakeRamassageStatutModel_9(
          this,
          Invocation.method(
            #updateRamassageStatut,
            [id],
          ),
        )),
        returnValueForMissingStub: _i20.Future<_i10.RamassageStatutModel>.value(
            _FakeRamassageStatutModel_9(
          this,
          Invocation.method(
            #updateRamassageStatut,
            [id],
          ),
        )),
      ) as _i20.Future<_i10.RamassageStatutModel>);

  @override
  _i20.Future<List<_i29.Ramassage>> getFinishedRamassageList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFinishedRamassageList,
          [],
        ),
        returnValue:
            _i20.Future<List<_i29.Ramassage>>.value(<_i29.Ramassage>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i29.Ramassage>>.value(<_i29.Ramassage>[]),
      ) as _i20.Future<List<_i29.Ramassage>>);

  @override
  _i20.Future<List<_i30.Depot>> getDepotList() => (super.noSuchMethod(
        Invocation.method(
          #getDepotList,
          [],
        ),
        returnValue: _i20.Future<List<_i30.Depot>>.value(<_i30.Depot>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i30.Depot>>.value(<_i30.Depot>[]),
      ) as _i20.Future<List<_i30.Depot>>);

  @override
  _i20.Future<_i11.Rdv> getDepotDetailComplet(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getDepotDetailComplet,
          [id],
        ),
        returnValue: _i20.Future<_i11.Rdv>.value(_FakeRdv_10(
          this,
          Invocation.method(
            #getDepotDetailComplet,
            [id],
          ),
        )),
        returnValueForMissingStub: _i20.Future<_i11.Rdv>.value(_FakeRdv_10(
          this,
          Invocation.method(
            #getDepotDetailComplet,
            [id],
          ),
        )),
      ) as _i20.Future<_i11.Rdv>);

  @override
  _i20.Future<_i12.PlannedDepotModel> planifierDepot(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #planifierDepot,
          [id],
        ),
        returnValue:
            _i20.Future<_i12.PlannedDepotModel>.value(_FakePlannedDepotModel_11(
          this,
          Invocation.method(
            #planifierDepot,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i12.PlannedDepotModel>.value(_FakePlannedDepotModel_11(
          this,
          Invocation.method(
            #planifierDepot,
            [id],
          ),
        )),
      ) as _i20.Future<_i12.PlannedDepotModel>);

  @override
  _i20.Future<List<_i30.Depot>> getPlanifiedDepotList() => (super.noSuchMethod(
        Invocation.method(
          #getPlanifiedDepotList,
          [],
        ),
        returnValue: _i20.Future<List<_i30.Depot>>.value(<_i30.Depot>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i30.Depot>>.value(<_i30.Depot>[]),
      ) as _i20.Future<List<_i30.Depot>>);

  @override
  _i20.Future<List<_i30.Depot>> getFinishedDepotList() => (super.noSuchMethod(
        Invocation.method(
          #getFinishedDepotList,
          [],
        ),
        returnValue: _i20.Future<List<_i30.Depot>>.value(<_i30.Depot>[]),
        returnValueForMissingStub:
            _i20.Future<List<_i30.Depot>>.value(<_i30.Depot>[]),
      ) as _i20.Future<List<_i30.Depot>>);

  @override
  _i20.Future<dynamic> getActivityDetails({
    required String? type,
    required int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivityDetails,
          [],
          {
            #type: type,
            #id: id,
          },
        ),
        returnValue: _i20.Future<dynamic>.value(),
        returnValueForMissingStub: _i20.Future<dynamic>.value(),
      ) as _i20.Future<dynamic>);
}

/// A class which mocks [WalletService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletService extends _i1.Mock implements _i31.WalletService {
  @override
  _i20.Future<_i13.WalletModel> getWalletSold() => (super.noSuchMethod(
        Invocation.method(
          #getWalletSold,
          [],
        ),
        returnValue: _i20.Future<_i13.WalletModel>.value(_FakeWalletModel_12(
          this,
          Invocation.method(
            #getWalletSold,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i13.WalletModel>.value(_FakeWalletModel_12(
          this,
          Invocation.method(
            #getWalletSold,
            [],
          ),
        )),
      ) as _i20.Future<_i13.WalletModel>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i32.ChatService {
  @override
  _i20.Future<Map<String, dynamic>?> getCurrentUserInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserInfo,
          [],
        ),
        returnValue: _i20.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i20.Future<Map<String, dynamic>?>.value(),
      ) as _i20.Future<Map<String, dynamic>?>);

  @override
  _i20.Future<String?> createOrGetConversation({
    required String? currentUserId,
    required String? clientId,
    required String? clientName,
    String? tripId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrGetConversation,
          [],
          {
            #currentUserId: currentUserId,
            #clientId: clientId,
            #clientName: clientName,
            #tripId: tripId,
          },
        ),
        returnValue: _i20.Future<String?>.value(),
        returnValueForMissingStub: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);

  @override
  _i20.Future<void> sendMessage({
    required String? conversationId,
    required String? senderId,
    required String? receiverId,
    required String? message,
    String? messageType = r'text',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #conversationId: conversationId,
            #senderId: senderId,
            #receiverId: receiverId,
            #message: message,
            #messageType: messageType,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Stream<_i33.QuerySnapshot<Object?>> getMessages(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [conversationId],
        ),
        returnValue: _i20.Stream<_i33.QuerySnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i20.Stream<_i33.QuerySnapshot<Object?>>.empty(),
      ) as _i20.Stream<_i33.QuerySnapshot<Object?>>);

  @override
  _i20.Future<void> markMessagesAsRead({
    required String? conversationId,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessagesAsRead,
          [],
          {
            #conversationId: conversationId,
            #currentUserId: currentUserId,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> startTyping({
    required String? conversationId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTyping,
          [],
          {
            #conversationId: conversationId,
            #userId: userId,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> stopTyping({
    required String? conversationId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopTyping,
          [],
          {
            #conversationId: conversationId,
            #userId: userId,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Stream<_i33.DocumentSnapshot<Object?>> getTypingStatus(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTypingStatus,
          [conversationId],
        ),
        returnValue: _i20.Stream<_i33.DocumentSnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i20.Stream<_i33.DocumentSnapshot<Object?>>.empty(),
      ) as _i20.Stream<_i33.DocumentSnapshot<Object?>>);

  @override
  bool isOtherUserTyping({
    required Map<String, dynamic>? conversationData,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isOtherUserTyping,
          [],
          {
            #conversationData: conversationData,
            #currentUserId: currentUserId,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i20.Future<void> cleanupOldTypingStatus(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupOldTypingStatus,
          [conversationId],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PickersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPickersService extends _i1.Mock implements _i34.PickersService {
  @override
  _i20.Future<Map<String, String>> getAuthenticatedHeaders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthenticatedHeaders,
          [],
        ),
        returnValue: _i20.Future<Map<String, String>>.value(<String, String>{}),
        returnValueForMissingStub:
            _i20.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i20.Future<Map<String, String>>);

  @override
  _i20.Future<_i14.RamasseurDemand> getRamassageList() => (super.noSuchMethod(
        Invocation.method(
          #getRamassageList,
          [],
        ),
        returnValue:
            _i20.Future<_i14.RamasseurDemand>.value(_FakeRamasseurDemand_13(
          this,
          Invocation.method(
            #getRamassageList,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i14.RamasseurDemand>.value(_FakeRamasseurDemand_13(
          this,
          Invocation.method(
            #getRamassageList,
            [],
          ),
        )),
      ) as _i20.Future<_i14.RamasseurDemand>);

  @override
  _i20.Future<_i14.RamasseurDemand> getActivityList() => (super.noSuchMethod(
        Invocation.method(
          #getActivityList,
          [],
        ),
        returnValue:
            _i20.Future<_i14.RamasseurDemand>.value(_FakeRamasseurDemand_13(
          this,
          Invocation.method(
            #getActivityList,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i14.RamasseurDemand>.value(_FakeRamasseurDemand_13(
          this,
          Invocation.method(
            #getActivityList,
            [],
          ),
        )),
      ) as _i20.Future<_i14.RamasseurDemand>);

  @override
  _i20.Future<void> acceptRamassage(
    int? id,
    _i19.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptRamassage,
          [
            id,
            context,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<_i15.RamasseurDemandDetail> getCurrentRamassageDetails(
    int? id,
    _i19.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentRamassageDetails,
          [
            id,
            context,
          ],
        ),
        returnValue: _i20.Future<_i15.RamasseurDemandDetail>.value(
            _FakeRamasseurDemandDetail_14(
          this,
          Invocation.method(
            #getCurrentRamassageDetails,
            [
              id,
              context,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i15.RamasseurDemandDetail>.value(
                _FakeRamasseurDemandDetail_14(
          this,
          Invocation.method(
            #getCurrentRamassageDetails,
            [
              id,
              context,
            ],
          ),
        )),
      ) as _i20.Future<_i15.RamasseurDemandDetail>);

  @override
  _i20.Future<_i16.FactureRamassageModel> getPickerFacture(
    int? id,
    double? poids,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPickerFacture,
          [
            id,
            poids,
          ],
        ),
        returnValue: _i20.Future<_i16.FactureRamassageModel>.value(
            _FakeFactureRamassageModel_15(
          this,
          Invocation.method(
            #getPickerFacture,
            [
              id,
              poids,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i20.Future<_i16.FactureRamassageModel>.value(
                _FakeFactureRamassageModel_15(
          this,
          Invocation.method(
            #getPickerFacture,
            [
              id,
              poids,
            ],
          ),
        )),
      ) as _i20.Future<_i16.FactureRamassageModel>);
}
